#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Downloads the UEFI Secure Boot iPXE chain + wimboot into the Deploy Manager TFTP root.

.DESCRIPTION
    Since iPXE v2.0.0 the project ships a Secure Boot chain that needs NO key
    enrollment, NO firmware changes and NO custom signing:

        UEFI firmware
          -> ipxe-shim.efi   (Microsoft-signed shim; trusted by default)
          -> ipxe.efi        (signed by the iPXE Secure Boot CA embedded in the shim)
          -> boot.ipxe       (HTTP boot script generated by Deploy Manager)
          -> wimboot         (Secure Boot capable; loads WinPE over HTTP)
          -> WinPE / Windows boot manager (Microsoft-signed)

    The shim is a Microsoft-signed fork of rhboot/shim that trusts only the iPXE
    Secure Boot CA. It derives the second-stage filename from its own name, so a
    copy named 'ipxe-shim.efi' loads 'ipxe.efi', and 'snponly-shim.efi' loads
    'snponly.efi'. Both stages must sit together in the TFTP root.

    Files placed in the TFTP root:
      ipxe-shim.efi    - UEFI Secure Boot first stage  (DHCP option 67 for UEFI)
      ipxe.efi         - iPXE, full driver set          (loaded by ipxe-shim.efi)
      snponly-shim.efi - alt first stage (UEFI SNP driver only)
      snponly.efi      - iPXE, SNP-only                 (loaded by snponly-shim.efi)
      undionly.kpxe    - legacy BIOS iPXE               (DHCP option 67 for BIOS)
      wimboot          - WIM boot loader                (loads WinPE over HTTP)

    You cannot rebuild iPXE with extra features and keep it Secure Boot trusted -
    the shim trusts only binaries the iPXE project itself signs. Use the shipped
    ipxe.efi / snponly.efi as-is. This is by design of UEFI Secure Boot.

.PARAMETER TftpRoot
    Path to the Deploy Manager TFTP root directory.
    Defaults to C:\ProgramData\DeployManager\tftp.

.PARAMETER IpxeVersion
    iPXE release tag to pull the signed chain from. Pinned for a reproducible,
    known-good shim/ipxe pairing. Bump this to adopt a newer signed release.

.NOTES
    Keep this file ASCII (the build validates it). Windows PowerShell 5.1 reads
    a BOM-less UTF-8 file as CP1252 and mis-parses non-ASCII characters.
#>
param(
    [string]$TftpRoot    = (Join-Path $env:ProgramData 'DeployManager\tftp'),
    [string]$IpxeVersion = 'v2.0.0'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "Deploy Manager - Secure Boot iPXE chain downloader"
Write-Host "TFTP root   : $TftpRoot"
Write-Host "iPXE release: $IpxeVersion"
Write-Host ""

# Use the in-box bsdtar by full path. Calling it by bare name risks picking up
# a GNU tar from the PATH (e.g. Git for Windows), which misreads 'C:\path' as a
# remote host. bsdtar handles Windows paths and gzip archives natively.
$tarExe = Join-Path $env:SystemRoot 'System32\tar.exe'
if (-not (Test-Path $tarExe)) {
    Write-Error "$tarExe not found. Windows Server 2019+/Windows 10 1803+ include it. Cannot extract the iPXE release."
    exit 1
}

if (-not (Test-Path $TftpRoot)) {
    New-Item -ItemType Directory -Path $TftpRoot -Force | Out-Null
    Write-Host "Created TFTP root directory."
}

# Force TLS 1.2 for HTTPS downloads (Server 2022 defaults can omit it under StrictMode).
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12

$work = Join-Path ([System.IO.Path]::GetTempPath()) ("ipxe-sb-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $work -Force | Out-Null

try {
    # -- 1. Download the signed iPXE boot bundle --------------------------------
    $tarball = Join-Path $work 'ipxeboot.tar.gz'
    $tarUrl  = "https://github.com/ipxe/ipxe/releases/download/$IpxeVersion/ipxeboot.tar.gz"
    Write-Host ("  Downloading ipxeboot.tar.gz ({0})..." -f $IpxeVersion) -NoNewline
    Invoke-WebRequest -Uri $tarUrl -OutFile $tarball -UseBasicParsing -TimeoutSec 180
    Write-Host (" OK ({0:N0} KB)" -f ((Get-Item $tarball).Length / 1KB)) -ForegroundColor Green

    # -- 2. Extract only the real files we need ---------------------------------
    # The archive uses symlinks (ipxe-shim.efi -> shimx64.efi) that cannot be
    # created on Windows without privilege, so extract the concrete members only
    # and make our own named copies below.
    $members = @(
        'ipxeboot/x86_64-sb/shimx64.efi',   # Microsoft-signed shim
        'ipxeboot/x86_64-sb/ipxe.efi',      # iPXE, full drivers  (SB signed)
        'ipxeboot/x86_64-sb/snponly.efi',   # iPXE, SNP only      (SB signed)
        'ipxeboot/x86_64/undionly.kpxe'     # legacy BIOS iPXE
    )
    Write-Host "  Extracting signed binaries..." -NoNewline
    & $tarExe -xzf $tarball -C $work @members
    if ($LASTEXITCODE -ne 0) { throw "tar extraction failed (exit $LASTEXITCODE)." }
    Write-Host " OK" -ForegroundColor Green

    $sbDir  = Join-Path $work 'ipxeboot/x86_64-sb'
    $binDir = Join-Path $work 'ipxeboot/x86_64'

    # -- 3. Place files in the TFTP root with the names the chain expects -------
    # The shim picks its second stage from its OWN filename (strip '-shim'), so
    # the shim binary is copied twice under two names.
    $place = @(
        @{ Src = Join-Path $sbDir  'shimx64.efi';   Dst = 'ipxe-shim.efi';    Desc = 'UEFI Secure Boot shim -> ipxe.efi' },
        @{ Src = Join-Path $sbDir  'ipxe.efi';      Dst = 'ipxe.efi';         Desc = 'iPXE (full drivers, SB signed)' },
        @{ Src = Join-Path $sbDir  'shimx64.efi';   Dst = 'snponly-shim.efi'; Desc = 'UEFI Secure Boot shim -> snponly.efi' },
        @{ Src = Join-Path $sbDir  'snponly.efi';   Dst = 'snponly.efi';      Desc = 'iPXE (SNP only, SB signed)' },
        @{ Src = Join-Path $binDir 'undionly.kpxe'; Dst = 'undionly.kpxe';    Desc = 'legacy BIOS iPXE' }
    )
    foreach ($p in $place) {
        if (-not (Test-Path $p.Src)) { throw "Expected file missing from archive: $($p.Src)" }
        Copy-Item -Path $p.Src -Destination (Join-Path $TftpRoot $p.Dst) -Force
        Write-Host ("    {0,-18} {1}" -f $p.Dst, $p.Desc) -ForegroundColor Gray
    }

    # -- 4. wimboot (Secure Boot capable; loads WinPE over HTTP) -----------------
    Write-Host "  Downloading wimboot (latest)..." -NoNewline
    Invoke-WebRequest -Uri 'https://github.com/ipxe/wimboot/releases/latest/download/wimboot' `
        -OutFile (Join-Path $TftpRoot 'wimboot') -UseBasicParsing -TimeoutSec 120
    Write-Host (" OK ({0:N0} KB)" -f ((Get-Item (Join-Path $TftpRoot 'wimboot')).Length / 1KB)) -ForegroundColor Green
}
finally {
    Remove-Item $work -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "Secure Boot iPXE chain installed." -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Configure your DHCP server:"
Write-Host "       - Option 66 (TFTP server): IP address of this server"
Write-Host "       - Option 67 (boot file):"
Write-Host "           UEFI clients : ipxe-shim.efi   (works with Secure Boot ON or OFF)"
Write-Host "           BIOS clients : undionly.kpxe"
Write-Host "  2. Add a DHCP user-class rule so already-booted iPXE clients"
Write-Host "     (user-class = iPXE) receive boot file:"
Write-Host "           http://<this-server>:8080/boot.ipxe"
Write-Host "     This breaks the loop (iPXE -> shim -> iPXE -> ...)."
Write-Host "  3. No Secure Boot changes are required on the clients: the shim is"
Write-Host "     Microsoft-signed and loads the iPXE-signed ipxe.efi automatically."
Write-Host "  4. Refresh Settings > Boot Image in Deploy Manager to confirm status."
